version: "3.8"
services:
  db:
    image: postgres:14
    container_name: notes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: notes-api
    container_name: notes-api
    environment:
      # DATABASE_URL:postgres://youruser:yourpassword@postgres:5432/yourdatabase
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/notes-db
    volumes:
      # - /path/to/your/development/folder:/app- /path/to/your/development/folder:/app
      - ${DEVELOPMENT_FOLDER}:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
